export const BrazilFederationsMongoList = [  
  "SP - SÃO PAULO",
  "RJ - RIO DE JANEIRO",
  "RS - RIO GRANDE DO SUL",
  "MG - MINAS GERAIS",
  "DF - DISTRITO FEDERAL",
  "PR - PARANÁ",
  "SC - SANTA CATARINA",
  "PE - PERNAMBUCO",
  "BA - BAHIA",
  "CE - CEARÁ",
  "GO - GOIÁS",
  "MS - MATO GROSSO DO SUL",
  "RN - RIO GRANDE DO NORTE",
  "ES - ESPÍRITO SANTO",
  "PA - PARÁ",
  "AM - AMAZONAS",
  "PB - PARAÍBA",
  "SE - SERGIPE",
  "MT - MATO GROSSO",
  "PI - PIAUÍ",
  "AL - ALAGOAS",
  "MA - MARANHÃO",
  "RO - RONDÔNIA",
  "RR - RORAIMA",
  "AC - ACRE",
  "TO - TOCANTINS",
  "AP - AMAPÁ"    
];
